### ISSUE TITLE
Removing layers doesn't work with MarkerCluster

### ISSUE THREAD

**Issue by darthsteven** [ghybs/Leaflet.FeatureGroup.SubGroup#11]
I have an application that needs to remove layers from the group, and have the parent group get updated.

This works fine if the parent group is, for example, the map or another layer group.

However, if the parent group is the [markercluster](https://github.com/Leaflet/Leaflet.markercluster) then this doesn't work.

This is because the markercluster is expecting a fully loaded layer object to be passed to removeLayer, instead it's passed the ID of the layer, which fails to remove it as far as I can see.

**Comment by darthsteven** [comment]
It does seem like the code should handle that case though, trying to work out what's up.

**Comment by darthsteven** [comment]
Ah no, sorry, yeah, it always passes the numeric ID of the layer to remove, which isn't handled very well by markercluster.

**Comment by darthsteven** [comment]
Not sure if I should suggest that MarkerCluster should support removal by ID rather than Layer object, but as the fix here is super easy, I'm going to fork and suggest the change.

**Comment by ghybs** [comment]
Hi,

Thank you for your report and for the PR!

Good catch about MCG not handling `removeLayer(layerId)`.
Indeed an easy fix would be to retrieve back the full layer object before calling `removeLayer`, as done internally in Leaflet LayerGroup.

Looking at my code I see another inconsistency, hopefully I can fix that later on.
I will merge your PR in the meantime.

Thank you for your contribution!
