### ISSUE TITLE
Demo page maps are non-functional

### ISSUE THREAD

**Issue by abea** [ghybs/Leaflet.FeatureGroup.SubGroup#2]
When I went to the demo links, the maps didn't work since GH pages is https and the CDN is http: https://github.com/ghybs/Leaflet.FeatureGroup.SubGroup/blob/master/README.md#demos

**Comment by ghybs** [comment]
Hi!

Thank you for the notification.

Strange, I have specified the `http://` protocol in the link, so you should have been directed to the HTTP version…

Please which browser do you use?
Do you have any extension that converts the protocol automatically?

**Comment by abea** [comment]
No extensions should be doing that. I'm working on Firefox Dev Edition, and it looks like vanilla FF (with no extensions) has the same behavior. All other normal browsers on my Mac show the maps alright.

Thanks for the plugin, as well. It just saved me a lot of headache.

**Comment by ghybs** [comment]
Thank you for the details.

Could it be related to these?
- [HTTP Strict Transport Security](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security)
- [HTTPS Everywhere extension](https://www.eff.org/https-everywhere)

Still, I will use alternate HTTPS CDN for Leaflet next time I update the demo pages.
Feel free to submit a PR by the way!

Thank you for your feedback on this plugin! :-)

**Comment by abea** [comment]
I'm sorry. I did have HTTPS Everywhere enabled. That was the issue.
